Police.Web.Common/Infrastructure/BaseViewComponent.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Police.Security.User;

namespace Police.Web.Common.Infrastructure {

    public abstract class BaseViewComponent : ViewComponent {

        protected readonly IMediator Mediator;
        protected readonly IUserService UserService;

        protected BaseViewComponent(
            IMediator mediator,
            IUserService userService) {
            Mediator = mediator;
            UserService = userService;
        }

        protected async Task<Guid> FetchCurrentUserId() =>
            (await FetchCurrentUser())?.UserId ?? Guid.Empty;

        protected async Task<UserInformation> FetchCurrentUser() =>
            await UserService.GetUserInformationForClaimsPrincipal(HttpContext.User);

    }

}

Police.Web.Common/Pages/Shared/Components/Navigation/NavigationViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Police.Security.User;
using Police.Web.Common.Navigation;

namespace Police.Web.Common.Pages.Shared.Components.Navigation {

    [ViewComponent(Name = "Navigation")]
    public class NavigationViewComponent : ViewComponent {

        public class NavBarViewModel {

            public UserInformation User { get; set; }
            public IEnumerable<NavigationSection> Sections { get; set; }

        }

        private readonly IEnumerable<INavigationSectionProvider> _navigationSectionProviders;
        private readonly IUserService _userService;

        public NavigationViewComponent(
            IEnumerable<INavigationSectionProvider> navigationSectionProviders,
            IUserService userService) {

            _navigationSectionProviders = navigationSectionProviders;
            _userService = userService;
        }

        public async Task<IViewComponentResult> InvokeAsync(bool forHomePage = false) {

            var navigationSections = new List<NavigationSection>();

            foreach (var navigationSectionProvider in _navigationSectionProviders) {

                navigationSections.Add(await navigationSectionProvider.GenerateNavigationSection());

            }

            if (forHomePage) {
                return View("ForHomePage", navigationSections);
            }

            return View(new NavBarViewModel {
                User = await _userService.GetUserInformationForClaimsPrincipal(HttpContext.User),
                Sections = navigationSections
            });

        }

    }

}

Police.Web.Common/Pages/Shared/Components/Navigation/Default.cshtml
@model NavigationViewComponent.NavBarViewModel

<nav class="navbar navbar-static-top" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <a asp-page="/" class="navbar-brand">
                <strong>Police</strong>
            </a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <i class="fa fa-bars"></i>
            </button>
        </div>
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
            <ul class="nav navbar-nav">

                @foreach (var navigationSection in Model.Sections) {

                    <li class="dropdown">

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            @navigationSection.Title <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">

                            @foreach (var navigationItem in navigationSection.NavigationItems) {

                                <li>
                                    <a asp-area="@navigationItem.Area" asp-page="@navigationItem.Page">@navigationItem.ShortTitle</a>
                                </li>

                            }

                        </ul>

                    </li>

                }

            </ul>


        </div>
        <environment include="Development">
            <div class="collapse navbar-collapse pull-right" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>

                        <a asp-controller="UserCache" asp-action="FlushUserCache">
                            <i class="fa fa-recycle"></i> Flush Cache
                        </a>

                    </li>
                    
                    <li style="background-color: #dd4b39;">
                        <a href="#">Development Mode</a>
                    </li>

                </ul>

            </div>
        </environment>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span>
                            <i class="fa fa-user"></i> @Model.User.UserName
                        </span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <i class="fa fa-user fa-5x text-center"></i>
                            <p>
                                <small>@Model.User.EmailAddress</small>
                                <strong>@Model.User.UserName</strong>
                            </p>
                        </li>
                        <li class="user-body">
                            <strong>Roles: </strong>
                            @foreach (var role in Model.User.EffectiveRoles) {
                                <span class="label label-default">@role.RoleName</span>
                            }
                        </li>
                        <li class="user-footer">
                        </li>
                    </ul>
                </li>
            </ul>
        </div>



    </div>


</nav>

Police.Web.Common/Pages/Shared/Components/Navigation/ForHomePage.cshtml
@model IEnumerable<Police.Web.Common.Navigation.NavigationSection>

@foreach (var navigationSection in Model) {

    <div class="col-xs-4">
        <div class="box box-solid box-success">
            <div class="box-header with-border">
                <h3 class="box-title">@navigationSection.Title</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

                @foreach (var navigationItem in navigationSection.NavigationItems) {

                    <a type="button"
                           class="btn btn-lg btn-info btn-block"
                           asp-area="@navigationItem.Area"
                           asp-page="@navigationItem.Page">
                            @navigationItem.Title
                        </a>

                }

            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>

}

Police.Web.Common/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Response to Resistance</title>
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/css/vendor.min.css" />
        <link rel="stylesheet" href="~/css/app.min.css" />
    </environment>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="skin-blue layout-top-nav">
    <environment names="Development">
        <mini-profiler position="@RenderPosition.BottomLeft" />
    </environment>

    <div class="wrapper">
        @RenderSection("modals", required: false)
        <header class="main-header">
            <vc:navigation for-home-page="false"></vc:navigation>
            @*<partial name="_Navigation" />*@

        </header>
        <div class="content-wrapper">
            <div class="container">
                <div class="row">
                    <section class="content-header">
                        <h1>
                            @RenderSection("header", required: false)
                        </h1>
                        <ol class="breadcrumb">
                            @RenderSection("breadcrumbs", required: false)
                        </ol>
                    </section>
                </div>
                <div class="row">
                    <section class="content">

                        <div id="modal-container">

                        </div>

                        @RenderBody()
                    </section>
                </div>
            </div>
        </div>
        <footer class="main-footer">
            <div class="container">
                <div class="pull-right hidden-xs">
                    <span class="text-danger" style="padding-left: 25px;">
                        <strong><i class="fa fa-warning"></i> Authorized Use Only</strong>
                    </span> |
                    <b>Version </b> 1.0
                </div>
                <strong>
                    @if (DateTime.Now.Year > 2018) {
                        @Html.Raw("Copyright &copy; 2018-" + DateTime.Now.Year.ToString() + ", City of La Crosse.")
                    } else {
                        @Html.Raw("Copyright &copy; 2018, City of La Crosse.")
                    }
                </strong>
                All Rights Reserved.

            </div>
        </footer>
    </div>
    <environment names="Development,Staging,Production">
        <script src="~/js/vendor.min.js"></script>
        <script src="~/js/app.min.js"></script>
    </environment>
    @RenderSection("scripts", required: false)
</body>
</html>

Police.Web.Common/Pages/Shared/_ModalLayout.cshtml
<form method="post" asp-page="@(ViewContext.RouteData.Values["Page"])" autocomplete="off">

    <input type="hidden" name="ReferrerUrl" id="ReferrerUrl" value="@ViewData["ReferrerUrl"]" />

    <div id="modal" class="modal fade" role="dialog" tabindex="-1">
        <div class="modal-content">

            <div class="modal-header">
                @ViewData["Title"]
            </div>

            <div class="modal-body">

                @RenderBody()

            </div>

            <div class="modal-footer">
                <a role="button" class="btn btn-md btn-default" data-dismiss="modal">Cancel</a>
                @RenderSection("button", required: true)
            </div>

        </div>
    </div>


</form>

Police.Web.Common/Pages/Shared/_Navigation.cshtml
<nav class="navbar navbar-static-top" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <a asp-page="/" class="navbar-brand">
                <strong>Police</strong>
            </a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <i class="fa fa-bars"></i>
            </button>
        </div>
        <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
            <ul class="nav navbar-nav"></ul>


        </div>


    </div>


</nav>